# Generated by Django 2.1.7 on 2021-04-30 00:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20210429_2146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='created_at',
            field=models.DateField(blank=True, default=datetime.datetime(2021, 4, 29, 21, 55, 47, 519066)),
        ),
    ]
